<?php
/**
 * Created by PhpStorm.
 * User: pnghai179
 * Date: 24/06/2014
 * Time: 14:20
 */

/**
 * Class ClientTest
 */
class ClientTest extends PHPUnit_Framework_TestCase
{
    private $_username = '';
    private $_password = '';
    private $_apiUrl = '';

    /**
     * @group Integration Test
     */
    public function testAccessToken()
    {
        /**
         * @scenario Sign In Test
         */
        $cemsClient = new CEMS\Client($this->_username, $this->_password, $this->_apiUrl);
        $token = $cemsClient->getAccessToken();
        $this->assertEquals($token, $_ENV['API_KEY']);

    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        #TODO: encrypt critical data here
        $this->_username = $_ENV['CLIENT_EMAIL'];
        $this->_password = $_ENV['CLIENT_PASSWORD'];
        $this->_apiUrl = $_ENV['API_URL'];
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
