<?php
/**
 * Created by PhpStorm.
 * User: pnghai
 * Date: 04/07/2014
 * Time: 17:14
 */

/**
 * Class ResourceTest
 * @package CEMS\Test
 */
class ResourceTest extends PHPUnit_Framework_TestCase
{
    protected $_client;
    protected $_resource;
    protected $_collection;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        #TODO: encrypt critical data here
        $this->_client = new CEMS\Client($_ENV['API_KEY'], $_ENV['API_URL']);
    }

    private function testGetSingleResource()
    {

    }

    private function testFetchCollection()
    {
        #todo: return page num, cur page.
    }

    private function testCreateResource()
    {

    }

    private function testUpdateResource()
    {

    }

    private function testDeleteResource()
    {

    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
 