language: php
php:
- 5.3
- 5.4
- 5.5
env:
  global:
  - secure: NDAm4ZPCxHSuAiPUHvzm8u334pfLL49Eawy4VHQlKhArWb0XGUkh40e2127ml5QUQQj2UKxS7XSEsxWvxDC27Nw0nli82FPtOoi7xNYGlIrxjp/cGRnoaaQqZZ0d/bTyD/tARnLTWjuRlo4vFprm8xKJy7lugIq3F740rDMFy18=
  - secure: ArI2kGR1fpm7Z91zqj8ppPiR4kpT+0x4+R7tVOqwHmIyHhPVOo6bty7n7HFKzpM7pGcf2Ban+BcB772le0qLM9WCnN4Ty1reEqdjc8sL6E86q9UkGdA3pyec1pJh06aoLgsujunh/vwKP9u4YLwL3T7Xp4NWDeo9/tYeA9e4VeA=
  - secure: PJI2V57XZ43gKxUUFMomEa+G+ngZlPx1Wfy3AoRWNxQVu6+VU8EsAZYg9gCEtxPRdk+icQd5HbblMIJFXjRVddpjDCrXwYfmD/jMpAGtcAS3XOpd/cwIhqTJ1MWq7Kb5V6RouDP57c4J6vu/vQozwv3fjoPTQ8sERI5nsjOPNWU=
  - secure: mp786VZZsBmfnD7uIOyXAKHXJbI+PN15pgOeJO8woq8XRSBSfv+df9XJSgE0bahDvfLdFdVWpwkL8/ihbihSfWIRypLGH/iPfllyY6zQHPRGuyflDfZ/bhWKkMnnpnugqKgkJBO44rz0GVM9qPpLvK/BQPZdBFJdGSDMMrRk9PA=
before_install:
- cp phpunit.xml.sample phpunit.xml
- pear config-set auto_discover 1
- pear channel-discover pear.phpunit.de
- pear install --alldeps phpunit/PHPUnit
- pear install phpunit/PHP_CodeCoverage
- pear install phpunit/PHPUnit_MockObject
- phpenv rehash
- composer self-update
- composer update --lock
before_script:
- composer update
- composer install
script:
- phpunit
