language: php
php:
- 5.4
- 5.5
env:
  global:
  - secure: ivvgHewKVz+lbniE8GWKX3oiwix/ewzxpSLYQY7lXGn020OhKx5Kw3ZVHNbiuXn78Ma419Tx1HCmWBNMy7sZlK4xBFRUlkgq7rUpd9QpIIZ4d4fp5dU0B0GUEGMyJ3cg3FfRoZWp33l9BU7hiiSxDvRhQK19WCLBuGHxYe7EhZs=
  - secure: aKbPYEZML6puetX1Pkh22IPPo3ePcnKbxY6lG33u1hqXS9278H4e3F7wxmtCn1J2VRAvLfsbgiTN0K4AV5AJcrf19WJDA2IwmDOAqDgt7+g0qNY9jLp8bHhhix26dIZcKFjGMKnL1JR1kn1OUdWwCBKY10rMVAmFvBqaeIfqupI=
  - secure: KKUhrmmXGi5eFNC/Zv6XV4NWMc4OM0Km4UXWcVHjSO2oC9hqtRs/bED6mbTa1i5D3k1P/kh0VTzgNP64jEw6/Ns7Gk/S9FY2mmv6vFBFsCkS72sj/bgoezR+KtAYydqk7xKW6atErNyPrgVB+DQOZ11buxL0EkxFIqJViUS6Xx4=
  - secure: cQCzwc71c5J6n7ILWQNXDsu8iOB9DrmN+9H5u8C9XpQowyYaXrvXCnevvlIQpzlcH8qm5ulJH53bwjLVVV7MBQmPtXR3p41Cdifay6VwbU/20Kza0vRLW/Cywljs0qFqq54pfg0Kw4V4OJbTevzs8iJFmJfyH8y7MTn8S/ZlWXs=
before_install:
- cp phpunit.xml.sample phpunit.xml
- composer install
before_script:
- wget https://phar.phpunit.de/phpunit.phar
- sudo chmod +x phpunit.phar
- sudo mv phpunit.phar /usr/local/bin/phpunit
- phpenv rehash
- composer self-update
script:
- phpunit
