<?php
/**
 * Created by PhpStorm.
 * User: pnghai
 * Date: 04/07/2014
 * Time: 17:14
 */

namespace CEMS\Tests;
use CEMS;

/**
 * Class AbstractResourceTest
 * @package CEMS\Tests
 */
abstract class AbstractResourceTest extends \PHPUnit_Framework_TestCase
{
    protected $_client;
    protected $_resource;
    protected $_collection;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        #TODO: encrypt critical data here
        $this->_client = new CEMS\Client($_ENV['API_KEY'], $_ENV['API_URL']);
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
 