<?php
/**
 * Created by PhpStorm.
 * User: pnghai179
 * Date: 24/06/2014
 * Time: 14:20
 */
namespace CEMS\Tests;
use CEMS;
/**
 * Class ClientTest
 * @package CEMS\Tests
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @group Integration Test
     * @covers Client::__construct
     * @covers Client::getAccessToken
     */
    public function testAccessToken()
    {
        /**
         * @scenario Sign In Test
         */
        $cemsClient = new CEMS\Client($_ENV['CLIENT_EMAIL'], $_ENV['CLIENT_PASSWORD'], $_ENV['API_URL']);
        $token = $cemsClient->getAccessToken();
        $this->assertEquals($token, $_ENV['API_KEY']);

    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
